title: Hello, world! I'm Vasu Balla
description: My scratchpad on the web, describing my experience in Oracle world.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://r12dba.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Vasu Balla # add your name
author-img: vasu.jpeg # add your photo
about-author: I am a Cloud Architect with zeal to learn and wit to execute complex projects. Specialized in managing and migrating Oracle workloads to cloud. Opinions expressed here of my own not my employer # add description
social-twitter: r12dba # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: vasuballa # add your Github handle
social-linkedin: vasuballa # add your Linkedin handle
social-email: vasu[dot]balla@outlook.com # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
